# Generated by Django 4.1.3 on 2022-12-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
