# Generated by Django 4.1.3 on 2022-12-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_ratingmovie_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='watchers',
        ),
        migrations.DeleteModel(
            name='UserMovieRelations',
        ),
    ]
