# Generated by Django 4.1.3 on 2022-12-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='movie',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
