# Generated by Django 4.1.3 on 2022-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movies_watchers_delete_usermovierelations'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='shot',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='кадр'),
        ),
    ]
