# Generated by Django 4.1.3 on 2022-12-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movies_shot_movieshots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieShots',
            new_name='MovieShot',
        ),
    ]
