# Generated by Django 4.1.3 on 2022-12-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_comment_name_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='movies',
        ),
    ]
