# Generated by Django 4.1.3 on 2022-12-12 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movies_likes_usermovierelations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermovierelations',
            options={'ordering': ['?'], 'verbose_name': 'Отношения фильм пользователь', 'verbose_name_plural': 'Отношения фильм пользователь'},
        ),
        migrations.AlterField(
            model_name='usermovierelations',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Фильм'),
        ),
    ]
